#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Hao GONG

# Short bio or description (displayed in the header)
description: Professional personal homepage of Hao GONG. Dr. Hao GONG is a research scientist. His research interests primarily lie in machine/deep learning, computer vision and optimization, with application to autonomous driving, intelligent traffic and medical image analysis. 

keywords: hao gong, haogong, gonghao, gong hao, dr hao gong, dr gong hao, hao gong phd, gong hao phd

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: images/avatar2316x2628.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: gonghao8567@gmail.com
  facebook:
  flickr:
  github: gonghao67
  instagram: 
  linkedin: https://www.linkedin.com/in/gonghao67/
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: https://twitter.com/gonghao67
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:
# excerpt_separator: <!--more-->

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://gong-hao.com" # the base hostname & protocol for your site

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

#permalink: /:title/
permalink: /


# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
      - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
    #  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - command.txt
  - todo.txt
  - _temp/index.html
  - _temp/
